### ISSUE TITLE
Add a manifest option

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/depstar#1]
Maybe a new entry point that is uberjar-with-manifest?

**Comment by seancorfield** [comment]
If the main class is not `clojure.main`, then it must be (AOT) compiled, which means `classes` (or some other folder) needs to exist and be on the classpath, and the Clojure compiler needs to be invoked with that folder location bound to `*compile-path*`.

**Comment by stathissideris** [comment]
Upvote for this, would be super-useful for me because I'd like to distribute my desktop app as a single jar that can be launched via double-click in Windows.

**Comment by seancorfield** [comment]
Having looked at what it would take to automate this seamlessly (ensuring there's a directory to compile things into, running `compile`, adding that directory to the classpaths), I'm not really seriously considering this, unless someone wants to submit a PR. There are alternatives out there that handle manifests etc.

**Comment by seancorfield** [comment]
After mulling this some more, I'm going to close it "won't do". Manifests are not **needed** for the general case and I don't want to deal with AOT in `depstar`. Folks who really need that functionality should pick a richer JAR-maker.
