### ISSUE TITLE
depstar `2.1.297` doesn't seem to pick up jar-name from aliases:

### ISSUE THREAD

**Issue by slipset** [seancorfield/depstar#102]
https://github.com/slipset/deps-deploy/blob/master/deps.edn#L29 works as expected with depstar version 2.0.211, ie it produces a jar file named `deps-deploy.jar`

When upgrading to depstar version 2.1.297, it produces a directory named `:jar` which contains `file-name`

```
✔ ~/Documents/github.com/deps-deploy [37-up-deps L|✚ 2]
08:27 $ ls -ltr
total 56
-rw-r--r--  1 erik  staff  11218 Mar 16  2020 LICENSE
drwxr-xr-x  3 erik  staff     96 Mar 16  2020 src
drwxr-xr-x  3 erik  staff     96 Mar 16  2020 test
-rw-r--r--  1 erik  staff    888 Oct 22  2020 CHANGELOG.md
-rw-r--r--  1 erik  staff   3439 Sep 15 07:56 README.md
drwxr-xr-x  3 erik  staff     96 Sep 15 07:56 doc
-rw-r--r--  1 erik  staff   2064 Sep 15 08:20 deps.edn
-rw-r--r--  1 erik  staff   2060 Sep 15 08:27 pom.xml
✔ ~/Documents/github.com/deps-deploy [37-up-deps L|✚ 2]
08:27 $ clj -X:depstar
:group-id should probably be a reverse domain name, not just slipset
Synchronizing pom.xml
Updating pom.xml file to {slipset/deps-deploy {:mvn/version "0.1.5"}}
Building thin jar: :jar/file-name
Processing pom.xml for {slipset/deps-deploy {:mvn/version "0.1.5"}}
✔ ~/Documents/github.com/deps-deploy [37-up-deps L|✚ 2…1]
08:27 $ ls -ltr
total 56
-rw-r--r--  1 erik  staff  11218 Mar 16  2020 LICENSE
drwxr-xr-x  3 erik  staff     96 Mar 16  2020 src
drwxr-xr-x  3 erik  staff     96 Mar 16  2020 test
-rw-r--r--  1 erik  staff    888 Oct 22  2020 CHANGELOG.md
-rw-r--r--  1 erik  staff   3439 Sep 15 07:56 README.md
drwxr-xr-x  3 erik  staff     96 Sep 15 07:56 doc
-rw-r--r--  1 erik  staff   2064 Sep 15 08:20 deps.edn
-rw-r--r--  1 erik  staff   2060 Sep 15 08:27 pom.xml
drwxr-xr-x  3 erik  staff     96 Sep 15 08:27 :jar
✔ ~/Documents/github.com/deps-deploy [37-up-deps L|✚ 2…1]
08:27 $ ls -l :jar
total 16
-rw-r--r--  1 erik  staff  7918 Sep 15 08:27 file-name
✔ ~/Documents/github.com/deps-deploy [37-up-deps L|✚ 2…1]
08:29 $ jar -tf ':jar/file-name'
META-INF/MANIFEST.MF
deps_deploy/
deps_deploy/deps_deploy.clj
deps_deploy/maven_settings.clj
deps_deploy/gpg.clj
META-INF/
META-INF/maven/
META-INF/maven/slipset/
META-INF/maven/slipset/deps-deploy/
META-INF/maven/slipset/deps-deploy/pom.properties
META-INF/maven/slipset/deps-deploy/pom.xml
✔ ~/Documents/github.com/deps-deploy [37-up-deps L|✚ 2…1]
08:29 $
```

**Comment by seancorfield** [comment]
2.0.211 -> 2.1.279 is a pretty big jump -- can you narrow it down a bit further for me?

**Comment by seancorfield** [comment]
I suspect 2.1.253 will work but 2.1.267 will fail. I think I can see the change that broke things now.

**Comment by seancorfield** [comment]
When I refactored the option processing into the `task` ns, I combined the preprocessing (which looks up keywords in aliases) and some of the option defaulting, and now a few things are turned into strings _before_ the preprocessing step. Apologies. Will fix shortly and cut a new release.

**Comment by slipset** [comment]
Seems to break between 2.0.216 (which works) and 2.1.245 (which doesn't)
No need to apologise, stranger things have gone worse

**Comment by seancorfield** [comment]
Oh, interesting. So I broke it earlier than I thought, from looking at the git logs...

**Comment by seancorfield** [comment]
Fixed on **develop** if you want to try via a git dep?

**Comment by slipset** [comment]
Tested via git deps, and works. 

Thanks for the super quick turn around!

**Comment by seancorfield** [comment]
Cool. Will try to get a release cut later today.

**Comment by seancorfield** [comment]
FYI, this will be the last release of `depstar` -- as noted on the Clojure mailing list and on Slack, I plan to sunset `depstar` and encourage folks to switch to `tools.build` now that it has parity with `depstar` (specifically, now that `uber` has conflict handlers and I have released the log4j2 plugins cache handler as a separate library, from `depstar`'s code).

**Comment by seancorfield** [comment]
v2.1.303 has been released to Clojars for you!
