### ISSUE TITLE
Main-Class: option for uberjar

### ISSUE THREAD

**Issue by maxp** [seancorfield/depstar#14]
Would be great to have an option to specify main class in  uberjar manifest.

**Comment by seancorfield** [comment]
Can you explain the scenario where you'd need that? Given that `depstar` does not (and will not) do AOT compilation...

**Comment by maxp** [comment]
I compile main class separately.
My users prefer to use 'single binary' to run an application - `java -jar app.jar` without additional options.

That's only reason.

**Comment by seancorfield** [comment]
Fair enough. I'll probably restore the behavior I had in a branch where you could specify the main class name directly after the JAR file name.

**Comment by seancorfield** [comment]
@maxp Can you try master and see if the new `-m` / `--main` option does what you want?

**Comment by maxp** [comment]
Yes. it works!

**Comment by seancorfield** [comment]
Great. I'll cut 0.3.1 in the next few days.

**Comment by seancorfield** [comment]
Cutting 0.3.1 release now.
