### ISSUE TITLE
depstar to add files from the 'resources' dir

### ISSUE THREAD

**Issue by boschi** [seancorfield/depstar#27]
How can depstar add files from the 'resources' dir?
Currently it issues a warning like:
`{:warning "ignoring unknown file type", :path "/my/resources/path/to/one/of/the/files.something"}`

And currently there is no option to make it add the file to the JAR.

However my lib requires some files (e.g. JNI files) to be packed into the JAR....

**Comment by seancorfield** [comment]
How exactly are you constructing your classpath for running `depstar`? If `resources` is on your classpath, everything in that folder will be added to the JAR -- we rely on that heavily at work.

If you are adding specific _files_ to the classpath, that likely won't work because `depstar` won't know what to do with classpath entries that are not JAR or directory. But you can add a _directory_ to the classpath just fine.

**Comment by seancorfield** [comment]
@boschi Any updates on this, or shall I close this issue out?

**Comment by seancorfield** [comment]
Closing this out due to lack of response from @boschi

**Comment by boschi** [comment]
Sorry for the delayed response.
I was trying to use depstar as a "JAR builder for Clojure", and as such, I needed to add non-jar and non-[.class|.clj]  files to it, as resources (to be fetched using the ClassLoader), but, as I mentioned, depstar ignores those when packaging the files.
From you reply I understand that depstar is NOT intended to be used as I was trying, so it is ok to close this thread, as this is not an "issue".

**Comment by seancorfield** [comment]
At work, we use `depstar` to build JAR files containing non-`.clj` files from the `resources` folder all the time and it works just fine -- so you misunderstood my reply.

How exactly are you constructing your classpath for running `depstar`? i.e., what is in your `deps.edn` file and what aliases are you using when you run `depstar`?

If you want the contents of the `resources` folder added to the JAR file, _it must be on the classpath used when you run `depstar`_. There's an example of this in the README, specifically to include non-`.clj` files (the `public-html` folder).
