### ISSUE TITLE
Provided dependencies

### ISSUE THREAD

**Issue by shannoncolavita** [seancorfield/depstar#32]
I have a :scope "provided" dependency that's still being included in the uber jar, it looks like this is ignored?

**Comment by seancorfield** [comment]
`depstar` uses whatever classpath is present, given the aliases you use when running `depstar`.

The Clojure CLI (`clojure.tools.deps.alpha`) does not support `:scope` -- that's a Maven thing that isn't relevant to `deps.edn`.
