### ISSUE TITLE
Add classpath option to override environment that depstar runs in

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/depstar#34]
@borkdude has shown that it would be useful to be able to specify a `-P` / `--classpath` option to override the default runtime classpath (for use with Babashka -- but it's more widely applicable).

**Comment by puredanger** [comment]
that already exists in clj (`-Scp`) in case that's useful

**Comment by borkdude** [comment]
@puredanger This feature allows to separate the classpath from which the uberjar is created from the tool classpath.

**Comment by seancorfield** [comment]
README now has an example of passing in `--classpath "$(clojure -A:webassets -Spath)"` for this.

**Comment by borkdude** [comment]
Thanks!
