### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by stathissideris** [seancorfield/depstar#4]
What would be the best way to add a verbose mode where the current classpath is printed and also all the files that are added to the uberjar? I'm willing to work on this but I noticed there is no tools.cli -- would it be acceptable to add it as dependency to parse the passed command line options?

**Comment by seancorfield** [comment]
I'll give it some thought over the weekend. I would _prefer_ to keep `depstar` as minimal as possible and would rather not introduce command line argument processing (it's why there are separate `jar` and `uberjar` entry points, for example, and why I haven't added manifests etc). I figure other tools can handle the more complex cases, but a verbose option sounds useful.

**Comment by stathissideris** [comment]
I completely understand, so I wouldn't mind doing some "manual" cli options processing to make this possible. Maybe in a small util namespace that covers the simple cases?

**Comment by seancorfield** [comment]
How would you feel about controlling logging detail with a JVM property and/or environment variable? The property could be set in `deps.edn` easily enough. The environment variable could be used from the command line to override it.

**Comment by stathissideris** [comment]
You're right, that sounds a bit more viable because we wouldn't end up reimplementing some of tools.cli and would keep the deps minimal.

**Comment by seancorfield** [comment]
I've added a hook for this in 2abd3a4cb102160b700b79392d8e32568a6dab4d

Feel free to send a PR with whatever debug output you feel is appropriate based on `(when *debug* ...)` and I'll merge that in.
