### ISSUE TITLE
License files ignored

### ISSUE THREAD

**Issue by SevereOverfl0w** [seancorfield/depstar#41]
This can cause violations of the distribution of those licenses, for example:

https://apache.org/licenses/LICENSE-2.0.html

> You must give any other recipients of the Work or Derivative Works a copy of this License; and

https://choosealicense.com/licenses/lgpl-3.0/

> Accompany the Combined Work with a copy of the GNU GPL and this license document.

**Comment by seancorfield** [comment]
Since a `LICENSE` file will appear in nearly every dependency, what do you think is an appropriate way to combine them into the final JAR file?

**Comment by SevereOverfl0w** [comment]
Maven shade renames them iirc. There's prior art there.

**Comment by seancorfield** [comment]
Thanks. WIll take a look.

**Comment by seancorfield** [comment]
I couldn't find much information on how Maven shade handles various license files and I examined the source and could not deduce what it does from that either, so I explored a handful of "uber" JAR files I could find that seem to have been built with Maven and as far as I can tell, licenses and (copyright) notices are just concatenated together, and then there is an additional resource transformer for licenses which doesn't concatenate a file if it has already seen it.

So I changed `depstar` to concatenate `LICENSE`, `COPYRIGHT`, and `NOTICE` files (with optional `.txt` or `.md` suffices) and keep track of the (contents of) files it has seen so it avoids concatenating in duplicates.
