### ISSUE TITLE
pom.xml location can't be supplied and is hardcoded to working directory

### ISSUE THREAD

**Issue by RickMoynihan** [seancorfield/depstar#46]
When using depstar as an API to build multiple target jars it would be useful to provide an explicit location for "pom.xml" rather than assuming it is always located relative to the JVMs current working directory.  Allowing a `:pom-file` key to override this default would be useful.

This is where the value appears to be hardcoded:

https://github.com/seancorfield/depstar/blob/87a368a22b375988c73572bddbc3ce840d2071d2/src/hf/depstar/uberjar.clj#L457

**Comment by seancorfield** [comment]
Sounds reasonable. I'll try to get that done later today.
