### ISSUE TITLE
Uberjar doesn't work on Windows due to shelling out and quoting issue

### ISSUE THREAD

**Issue by borkdude** [seancorfield/depstar#57]
When trying to make an uberjar on Windows with depstar for [this](https://github.com/babashka/pod-babashka-buddy) project, I got:

```
main] INFO hf.depstar.uberjar - Compiling pod.babashka.buddy ...
Execution error at clojure.main/main (main.java:40).
Invalid token: C:
Full report at:
C:\Users\appveyor\AppData\Local\Temp\1\clojure-3649748013505680792.edn
[main] ERROR hf.depstar.uberjar - Compilation of pod.babashka.buddy failed!
```

You can reproduce this issue by checking out the project at commit SHA `cd98a0e331253e7d547febad8a3aa49ad2ff0cd8` and running `clojure -X:uberjar` (the arguments to depstar are provided in the deps.edn itself).

I suspected the error happened due to an odd behavior of shelling out on Windows using ProcessBuilder (and clojure.java.shell, etc): double quotes need to be escaped in shell arguments.

I've ran into this issue with several projects. Later on I made a library around ProcessBuilder which includes this fix for Windows automaticallly:

https://github.com/babashka/process/blob/ac1219508857d4b3106e5a7999a3573c61c7aa63/src/babashka/process.clj#L94-L101

I will provide a PR which fixes the issue in depstar for Windows by escaping double quotes in the shell arguments. I have already tested this solution and it fixed the problem.

You can verify that this PR works on Windows by checking out commit `423f14d33d0ceec1b339674b2b45cad415c08b8f` and running `clojure -X:uberjar` again.

**Comment by seancorfield** [comment]
Fixed via #58
