### ISSUE TITLE
When building an uberjar, make pom.xml optional

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/depstar#59]
It is not really needed. You can provide `:main-class` which is all that `MANIFEST.MF` needs in order to support `java -jar`.

If you provide `:group-id`, `:artifact-id`, and `:version`, `depstar` should be able to fill that information in without a `pom.xml` file -- but for backward compatibility, it should generate `pom.xml` (i.e., trigger `:sync-pom true` as it does today) unless you specify `:no-pom true`.

If you do not provide those three, it should not trigger `:sync-pom true` (double-check current behavior).

`depstar` should allow you to build uberjars without `pom.xml` being present.

**Comment by chrysophylax** [comment]
This'd be great since we only use tools.deps for  dependency management and generating an unused pom.xml feels bad.
