### ISSUE TITLE
Need compilation customization in depstar 2.x

### ISSUE THREAD

**Issue by atdixon** [seancorfield/depstar#63]
This may be somewhat of a specialized build use case (JavaFX builds), but my issue could be solved by a more general depstar feature.

Context: AOT compilation of JavaFX code requires a _post-compile_ invocation of `(javafx.application.Platform/exit)` or else the compile will hang waiting for UI system to exit. (More explanation can be found [here](https://github.com/cljfx/cljfx#aot-compilation-is-complicated).)

In depstar 1.x, compilation was done in-JVM, so I got by with a custom build fn that I could invoke from `deps.edn` via `:exec-fn`:

```
(defn run
  [& args]
  (try
    (apply hf.depstar/uberjar args)
    (finally
      (Platform/exit))))
```

([This](https://github.com/cljfx/hn/pull/3/files#diff-551f87f7577a57c2f4f74b35056d5c7985331f7a38976810fd2bbc213bfe7bb5R6) is what the `deps.edn` side looks like.)

In depstar 2.x, compilation is out-of-process, so this won't work.

Some options to consider...

*Option 1* One solution, if depstar 2.x could provide `:extra-jvm-args` (say). Then I could:

`:extra-jvm-args "-e (Platform/exit)"`

This would rely on running _after_ the `-e (binding,[*compile-path*, ...` that depstar provides to do the compilation.

Downside: would only work if compile step didn't throw. If build failed, I'd still have to kill the process.

*Option 2* 

More robust and flexible would be to allow depstar users to specify the compile form/function completely (with the assumption that depstar will compute & bind the `*compile-path*` before invoking our custom compile.

This option seems better as I type it out. What do you think?

**Comment by seancorfield** [comment]
It seems like there are two or possibly three "slots" that would benefit from hooks for additional compilation control:
* additional JVM options passed to `java` either prior to or immediately after the `-cp <classpath>` part, so you set JVM properties for example
* additional Clojure code executed after the `compile` call, such as `(Platform/exit)` above
* possibly additional Clojure code executed _before_ the `compile` call such as `require`/`import` to support the post-compile code

We'd end up with:
```bash
java <additional JVM options> -cp <classpath> -e "(binding [*compile-path* <tmp-c-dir>] (try <setup code> (compile '<sym>) (finally <teardown code>)))"
```

Your "option 2" sounds appealing but how would the `<sym>` to be compiled be passed into that form passed in? Bear in mind that `:compile-ns` takes a vector of namespaces to be compiled so the general cases is that this code block is going to be executed more than once, with different namespace symbols each time.

**Comment by atdixon** [comment]
Would this work?

A `:compile-fn` option (which by default is `clojure.core/compile`) but otherwise could be a fully-qualified function name.

Just like `clojure.core/compile` the function would accept a symbol. depstar would have to auto-require the namespace (if it were not `clojure.core`).

But in this way, I would provide (say) `my.build/compile*` (ensuring that `my.build.ns` was in the `:replace-deps` path):

```
(ns my.build
   (:import (javafx.application Platform))
(defn compile* [lib]
   (try
      (compile lib)
      (finally 
         (Platform/exit))))
```

Of course `compile` would be invoked for every `:compile-ns` as it is now.

**Comment by seancorfield** [comment]
That's probably a good approach -- it feels like it fits with the general shift in Clojure tooling toward "function execution" and symbol resolution.

I suspect people will still want a way to provide one or more JVM options but I think I'll make that a separate ticket now.
