### ISSUE TITLE
Documentation mentions that :compile-ns accept :all, but I'm getting errors while trying to use

### ISSUE THREAD

**Issue by mauricioszabo** [seancorfield/depstar#68]
I was trying to use depstar, but when I tried to compile anything with `:compile-ns :all` I'm getting `keyword is not a sequence` error. Probably the error is because the code is using `filter` over the compile-ns form:

https://github.com/seancorfield/depstar/blob/develop/src/hf/depstar/uberjar.clj#L627-L628

I was also not able to use a regexp as parameter...

**Comment by seancorfield** [comment]
Ah, yes, there just aren't enough tests to trap that bug. I already tripped over `:aot true` being broken after merging the PR that added the regex and I hadn't noticed this was also broken. Will fix today.
