### ISSUE TITLE
Provide a way to supply different aliases to compile and build phases

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/depstar#75]
`agentfunk` on Slack is building a Storm topology and the app depends on the `storm-client.jar` for AOT compile but the uberjar does not need it (because the platform provides it).

Proposal: add `:compile-aliases` to allow a "compile basis" to be calculated and used for AOT compilation instead of the regular basis. Without this new option, the regular basis would be used for both phases.

This would allow for a `:storm` alias to be added to `agentfunk`'s `deps.edn` containing just the `storm-client.jar` (and remove it from the regular dependencies. That `:storm` alias would be required when doing dev/test locally and would be passed to `:compile-aliases [:storm]` so that AOT would use it. The JAR would then be built from the regular dependencies (without the `storm-client.jar` library).

**Comment by agentfunk** [comment]
@seancorfield much appreciated!
